version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtest
    mem_limit: "3g"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    mem_limit: "1g"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest
      - NEO4J_URI=bolt://neo4j:7687
      - JSON_FILE=/data/dblpv13.json # à modifier si besoin
    volumes:
      - C:\\Users\\denis.iglesias\\OneDrive - HESSO\\03 Master\\01 Cours\\12 TSM-AdvDaBa\\02 Labo\\03 Labo 2.2 neo4j large database:/data # à modifier si besoin
