version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: "1g"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest
      - NEO4J_URI=bolt://neo4j-service:7687
      - JSON_FILE=/data/dblpv13.json # Update as needed
    volumes:
      - C:\\Users\\denis.iglesias\\OneDrive - HESSO\\03 Master\\01 Cours\\12 TSM-AdvDaBa\\02 Labo\\03 Labo 2.2 neo4j large database:/data # à modifier si besoin
