version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    mem_limit: "1g"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest
      - NEO4J_URI=bolt://neo4j:7687
      - JSON_FILE=http://vmrum.isc.heia-fr.ch/dblpv13.json
      - BATCH_SIZE_ARTICLES=5000
      - BATCH_SIZE_APOC=5000
      - BUFFER_SIZE_PARSER=131072 # 128k