version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtest
      # - NEO4J_dbms_memory_heap_initial__size=768M
      # - NEO4J_dbms_memory_heap_max__size=768M
      # - NEO4J_dbms_memory_pagecache_size=512M
      # - NEO4J_dbms_memory_transaction_total_max=512M
      - NEO4J_PLUGINS=["apoc"]
    mem_limit: "16g"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    mem_limit: "1g"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest
      - NEO4J_URI=bolt://neo4j:7687
      - JSON_FILE=http://vmrum.isc.heia-fr.ch/dblpv13.json
      - BATCH_SIZE_ARTICLES=10000
