version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testtest
    mem_limit: "3g"  # Memory limit for neo4j

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    mem_limit: "1g"

