apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4jlarge-deployment
  namespace: adv-da-ba23-iglwae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4jlarge
  template:
    metadata:
      labels:
        app: neo4jlarge
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          env:
            - name: NEO4J_AUTH
              value: "neo4j/testtest"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
          ports:
            - containerPort: 7687
          resources:
            limits:
              memory: "3.5Gi"
