apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: adv-da-ba23-iglwae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: comfy2665/neo4j_large
          imagePullPolicy: Always
          env:
            - name: NEO4J_HOST
              value: "neo4jlarge-service"
            - name: NEO4J_PORT
              value: "7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "testtest"
            - name: NEO4J_URI
              value: "bolt://neo4jlarge-service:7687"
            - name: JSON_FILE
              value: "http://vmrum.isc.heia-fr.ch/dblpv13.json"
            - name: BATCH_SIZE_ARTICLES
              value: "1000"
          resources:
            limits:
              memory: "0.2Gi"
            requests:
              memory: "0.2Gi"

