apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: adv-da-ba23-iglwae
spec:
  containers:
  - name: temp-container
    image: nginx
    volumeMounts:
    - name: json-volume
      mountPath: "/mnt"
  volumes:
  - name: json-volume
    persistentVolumeClaim:
      claimName: json-data-pvc
